"""
Liste des tables d'agrégation par placette (``psdrfPla*``) à calculer pour
produire un carnet COMPLET.

Origine : ``data/reference_r/tabpla_names_r.txt`` du dépôt PermPSDRF4py (parité R,
97 tables). Ce fichier vit dans ``data/`` qui est gitignoré côté sous-module, donc
non disponible à l'exécution dans le module web : on fige la liste ici.

Sans cette liste, ``psdrf_agreg_arbres`` ne produit que ~9 tables d'aperçu
(``annexes.DEFAULT_TABLE_VARS``) et le carnet sort incomplet (chapitres BM/BV/CodeEco
qui consomment ``psdrfDisp*`` dérivées de ces ``psdrfPla*``).

Usage : ``results_by_plot_from_table_names(TABPLA_NAMES_CARNET)`` puis passer le
résultat à ``psdrf_agreg_arbres(..., results_by_plot_to_get=...)``.
"""

from __future__ import annotations

TABPLA_NAMES_CARNET: list[str] = [
    "psdrfPlaBM_",
    "psdrfPlaBM_Classe",
    "psdrfPlaBM_Essence",
    "psdrfPlaBM_EssenceClasse",
    "psdrfPlaBM_EssReg",
    "psdrfPlaBM_EssRegClasse",
    "psdrfPlaBM_StadeD",
    "psdrfPlaBM_StadeDStadeE",
    "psdrfPlaBM_StadeE",
    "psdrfPlaBMP_",
    "psdrfPlaBMP_Classe",
    "psdrfPlaBMP_ClasseStadeD",
    "psdrfPlaBMP_ClasseStadeE",
    "psdrfPlaBMP_ClasseType",
    "psdrfPlaBMP_Coupe",
    "psdrfPlaBMS_",
    "psdrfPlaBMS_Classe",
    "psdrfPlaBMS_ClasseStadeD",
    "psdrfPlaBMS_ClasseStadeE",
    "psdrfPlaBMS_Coupe",
    "psdrfPlaCodes_",
    "psdrfPlaCodes_Cat",
    "psdrfPlaCodes_CatCodeEcolo",
    "psdrfPlaCodes_CodeEcolo",
    "psdrfPlaCodes_EssenceCodeEcolo",
    "psdrfPlaDen_",
    "psdrfPlaDen_Cat",
    "psdrfPlaDen_CatCodeEcolo",
    "psdrfPlaDen_CatCoupe",
    "psdrfPlaDen_Classe",
    "psdrfPlaDen_ClasseCodeEcolo",
    "psdrfPlaDen_CodeEcolo",
    "psdrfPlaDen_CodeSanit",
    "psdrfPlaDen_Coupe",
    "psdrfPlaDen_Essence",
    "psdrfPlaDen_EssenceCat",
    "psdrfPlaDen_EssenceCatCoupe",
    "psdrfPlaDen_EssenceClasse",
    "psdrfPlaDen_EssenceCodeEcolo",
    "psdrfPlaDen_EssenceCodeSanit",
    "psdrfPlaDen_EssenceCoupe",
    "psdrfPlaDen_EssReg",
    "psdrfPlaDen_EssRegCat",
    "psdrfPlaDen_EssRegClasse",
    "psdrfPlaDen_EssRegCoupe",
    "psdrfPlaExploit_",
    "psdrfPlaExploit_Cat",
    "psdrfPlaExploit_Classe",
    "psdrfPlaExploit_Essence",
    "psdrfPlaFpied_",
    "psdrfPlaFpied_Cat",
    "psdrfPlaFpied_CatCodeEcolo",
    "psdrfPlaFpied_CatCoupe",
    "psdrfPlaFpied_Classe",
    "psdrfPlaFpied_ClasseCodeEcolo",
    "psdrfPlaFpied_CodeEcolo",
    "psdrfPlaFpied_Coupe",
    "psdrfPlaFpied_Essence",
    "psdrfPlaFpied_EssenceCat",
    "psdrfPlaFpied_EssenceClasse",
    "psdrfPlaFpied_EssenceCodeEcolo",
    "psdrfPlaFpied_EssReg",
    "psdrfPlaFpied_EssRegParCat",
    "psdrfPlaPer_",
    "psdrfPlaPer_Cat",
    "psdrfPlaPer_Classe",
    "psdrfPlaPer_Essence",
    "psdrfPlaPer_EssenceClasse",
    "psdrfPlaPer_EssReg",
    "psdrfPlaPer_EssRegClasse",
    "psdrfPlaPFutaie_",
    "psdrfPlaPFutaie_Cat",
    "psdrfPlaPFutaie_Classe",
    "psdrfPlaPFutaie_Essence",
    "psdrfPlaRege_",
    "psdrfPlaRege_Essence",
    "psdrfPlaRege_EssReg",
    "psdrfPlaRege_EssRegPar",
    "psdrfPlaTaillis_",
    "psdrfPlaTaillis_Cat",
    "psdrfPlaTaillis_Classe",
    "psdrfPlaTaillis_Essence",
    "psdrfPlaTaillis_EssenceClasse",
    "psdrfPlaTaillis_EssRegClasse",
    "psdrfPlaTot_",
    "psdrfPlaTot_Cat",
    "psdrfPlaTot_CatCodeEcolo",
    "psdrfPlaTot_CatCoupe",
    "psdrfPlaTot_Classe",
    "psdrfPlaTot_ClasseCoupe",
    "psdrfPlaTot_Coupe",
    "psdrfPlaTot_Essence",
    "psdrfPlaTot_EssenceClasse",
    "psdrfPlaTot_EssReg",
    "psdrfPlaTot_EssRegCat",
    "psdrfPlaTot_EssRegClasse",
    "psdrfPlaTot_EssRegParCat",
]

assert len(TABPLA_NAMES_CARNET) == 97, len(TABPLA_NAMES_CARNET)
